// ================================================================
//  TouchstoneCliVerbTests.cs — `circuitrf check` and `circuitrf explain` on an `.sNp`.
//
//  The verb split under test: `check` answers "is this file sound", `explain` answers "what IS
//  this part". They are gated together because the split is the design — a self-resonance is not a
//  defect and does not belong in a findings list, and a passivity violation is not a fact about the
//  part the user chose it for.
//
//  Assertions are on DIAGNOSTIC IDS, never on prose (R-aut1-8), except where the number itself is
//  the contract — `explain`'s resolved values are the answer, so those are read out of the JSON and
//  compared against a closed form.
//
//  Every fixture is generated here from an analytic R-L-C, never committed: a Touchstone file in
//  the repo would be a second copy of the physics, and a wrong one would pass silently. Paths are
//  temp folders with invented names.
//
//  The CLI is launched as the already-built CircuitRF.Cli.dll rather than `dotnet run --project`,
//  which hangs inside `dotnet test` (EmCliVerbTests.RunCli records why).
// ================================================================

using System.Diagnostics;
using System.Globalization;
using System.Numerics;
using System.Text.Json;
using Xunit.Abstractions;

namespace CircuitRF.Ui.Tests;

public class TouchstoneCliVerbTests(ITestOutputHelper output) : IDisposable
{
    private readonly string _dir = Directory.CreateTempSubdirectory("crf-touchstone-").FullName;

    public void Dispose()
    {
        try { Directory.Delete(_dir, recursive: true); } catch { /* a temp dir that outlives the run is not a failure */ }
        GC.SuppressFinalize(this);
    }

    // ── fixtures ───────────────────────────────────────────────────────────────────────────────

    private const double Z0  = 50.0;
    private const double Esr = 5e-3, Esl = 0.5e-9, Cap = 100e-9;

    /// <summary>1/(2π√(LC)) — 22.5079 MHz for the values above.</summary>
    private static double SrfHz => 1.0 / (2.0 * Math.PI * Math.Sqrt(Esl * Cap));

    /// <summary>A shunt-through MLCC on a log sweep — the shape of a vendor decoupling part file.</summary>
    private string WriteMlcc(string name = "part.s2p", int n = 601, double lo = 1e6, double hi = 1e9)
    {
        return WriteShunt(name, LogSweep(n, lo, hi), f =>
        {
            double w = 2.0 * Math.PI * f;
            return new Complex(Esr, w * Esl - 1.0 / (w * Cap));
        });
    }

    private static double[] LogSweep(int n, double lo, double hi) =>
        [.. Enumerable.Range(0, n).Select(i => lo * Math.Pow(hi / lo, i / (double)(n - 1)))];

    private string WriteShunt(string name, double[] f, Func<double, Complex> z) =>
        Write(name, f, fi =>
        {
            var Z = z(fi);
            var s21 = 2.0 * Z / (2.0 * Z + Z0);
            var s11 = -Z0 / (2.0 * Z + Z0);
            return (s11, s21, s21, s11);
        });

    private string Write(
        string name, double[] f,
        Func<double, (Complex S11, Complex S12, Complex S21, Complex S22)> body,
        double z0 = Z0)
    {
        string path = Path.Combine(_dir, name);
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("! generated by TouchstoneCliVerbTests");
        sb.AppendLine(FormattableString.Invariant($"# HZ S RI R {z0}"));
        foreach (double fi in f)
        {
            var (s11, s12, s21, s22) = body(fi);
            sb.AppendLine(string.Join(' ', new[] { fi, s11.Real, s11.Imaginary, s21.Real, s21.Imaginary,
                                                   s12.Real, s12.Imaginary, s22.Real, s22.Imaginary }
                .Select(v => v.ToString("G17", CultureInfo.InvariantCulture))));
        }
        File.WriteAllText(path, sb.ToString());
        return path;
    }

    // ── check ──────────────────────────────────────────────────────────────────────────────────

    [Fact]
    public void AWellFormedPassivePartChecksCleanAndStillReportsWhatItRead()
    {
        var run = RunCli("check", WriteMlcc(), "--json");

        Assert.Equal(0, run.ExitCode);
        // The summary is a NOTE and it is unconditional: a check that said nothing on a good file
        // leaves the caller unable to tell it ran.
        AssertHasDiagnostic(run, "check.touchstone.summary");
        Assert.Equal("2", Argument(Json(run), "check.touchstone.summary", "ports"));
    }

    [Fact]
    public void AnAmplifierFileIsReportedAsHavingGainAndAsNonReciprocal_AsWarningsNotErrors()
    {
        string p = Write("amp.s2p", LogSweep(50, 1e8, 1e10),
            _ => (new Complex(0.1, 0), new Complex(0.01, 0), new Complex(3.16, 0), new Complex(0.2, 0)));

        var run = RunCli("check", p, "--json");
        AssertHasDiagnostic(run, "check.touchstone.not-passive");
        AssertHasDiagnostic(run, "check.touchstone.not-reciprocal");

        // The whole severity argument in one assertion: nothing in a Touchstone file says the part
        // is meant to be passive, so an amplifier must not make `check` fail.
        Assert.Equal(0, run.ExitCode);
        Assert.Equal(1, RunCli("check", p, "--severity", "warning").ExitCode);
    }

    [Fact]
    public void ARepeatedFrequencyIsAnError_AndNamesThePoint()
    {
        double[] f = [1e9, 2e9, 2e9, 3e9];
        string p = Write("dup.s2p", f,
            _ => (new Complex(0.1, 0), new Complex(0.5, 0), new Complex(0.5, 0), new Complex(0.1, 0)));

        var run = RunCli("check", p, "--json");
        Assert.Equal(1, run.ExitCode);
        Assert.Equal("2", Argument(AssertHasDiagnostic(run, "check.touchstone.frequency-order"),
                                   "check.touchstone.frequency-order", "index"));
    }

    [Fact]
    public void ANonFiftyOhmReferenceIsReported_BecauseItIsCarriedSilentlyIntoEveryComparison()
    {
        string p = Write("part75.s2p", LogSweep(20, 1e8, 1e9),
            _ => (new Complex(0.1, 0), new Complex(0.5, 0), new Complex(0.5, 0), new Complex(0.1, 0)),
            z0: 75.0);

        var run = RunCli("check", p, "--json");
        AssertHasDiagnostic(run, "check.touchstone.z0-not-50");
        Assert.Equal(0, run.ExitCode);
    }

    [Fact]
    public void ALogSweepSaysCausalityCouldNotBeEvaluated_RatherThanPassingItInSilence()
    {
        AssertHasDiagnostic(RunCli("check", WriteMlcc(), "--json"), "check.touchstone.causality-skipped");
    }

    [Fact]
    public void AFileWhoseImpulseResponseRunsBackwardsIsFlagged()
    {
        // A uniform grid reaching DC in one step, carrying a 2 ns ADVANCE — the shape a model
        // fitted without a causality constraint produces.
        double[] f = [.. Enumerable.Range(1, 400).Select(k => k * 25e6)];
        string p = Write("acausal.s2p", f, fi =>
        {
            var s21 = Complex.Exp(new Complex(0, +2 * Math.PI * fi * 2e-9));
            return (Complex.Zero, s21, s21, Complex.Zero);
        });

        AssertHasDiagnostic(RunCli("check", p, "--json"), "check.touchstone.not-causal");
    }

    /// <summary>
    /// A folder walk does NOT check Touchstone files. A kit directory holds hundreds of them, and a
    /// walk that measured passivity and causality across all of them would bury the workspace's own
    /// findings under notes about parts the user did not author. Naming the file is what checks it.
    /// </summary>
    [Fact]
    public void AFolderWalkSkipsTouchstoneFiles_ButNamingOneChecksIt()
    {
        WriteMlcc("part.s2p", n: 40);

        var walk = RunCli("check", _dir, "--json");
        Assert.DoesNotContain("check.touchstone.summary", Ids(Json(walk)));

        AssertHasDiagnostic(RunCli("check", Path.Combine(_dir, "part.s2p"), "--json"),
                            "check.touchstone.summary");
    }

    // ── explain ────────────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// The headline of the `explain` half: the self-resonance and the impedance floor come back,
    /// and they are the numbers the part was BUILT from — checked against the closed form, not
    /// against another circuitRF path.
    /// </summary>
    [Fact]
    public void ExplainRecoversTheSelfResonanceAndTheEsrOfTheParticularPart()
    {
        var run = RunCli("explain", WriteMlcc(), "--json");
        Assert.Equal(0, run.ExitCode);
        output.WriteLine(run.StdOut);

        string srf = Step(Json(run), "SRF (shunt-through)")!;
        Assert.EndsWith(" MHz", srf, StringComparison.Ordinal);
        double mhz = double.Parse(srf[..^4], CultureInfo.InvariantCulture);
        Assert.InRange(mhz, SrfHz / 1e6 * 0.999, SrfHz / 1e6 * 1.001);

        // The floor is the ESR, in milliohms — a decoupling capacitor's whole selling point.
        Assert.Contains("ESR 5 mΩ", Step(Json(run), "|Z| min (shunt-through)"), StringComparison.Ordinal);
    }

    /// <summary>
    /// Both through readings are reported side by side rather than one being chosen. That is not
    /// indecision: nothing in the file records the fixture, and seeing both is the fastest way to
    /// tell which is physical — here the series reading finds no resonance at all and puts the
    /// floor three orders of magnitude out.
    /// </summary>
    [Fact]
    public void ExplainReportsEveryApplicableFixture_SoTheWrongOneIsObvious()
    {
        var doc = Json(RunCli("explain", WriteMlcc(), "--json"));

        Assert.NotNull(Step(doc, "SRF (shunt-through)"));
        Assert.Null(Step(doc, "SRF (series-through)"));      // no crossing under the wrong reading
        Assert.NotNull(Step(doc, "|Z| min (series-through)"));

        // And the rule is stated on every step, since the fixture is an assumption the file does
        // not record.
        Assert.Contains("SHUNT-through", How(doc, "SRF (shunt-through)"), StringComparison.Ordinal);
    }

    [Fact]
    public void AOnePortFileGetsTheOnePortReadingAndNoThroughReadings()
    {
        double[] f = LogSweep(401, 1e6, 1e9);
        string path = Path.Combine(_dir, "part.s1p");
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("! one-port MLCC");
        sb.AppendLine("# HZ S RI R 50");
        foreach (double fi in f)
        {
            double w = 2.0 * Math.PI * fi;
            var Z = new Complex(Esr, w * Esl - 1.0 / (w * Cap));
            var s11 = (Z - Z0) / (Z + Z0);
            sb.AppendLine(string.Join(' ', new[] { fi, s11.Real, s11.Imaginary }
                .Select(v => v.ToString("G17", CultureInfo.InvariantCulture))));
        }
        File.WriteAllText(path, sb.ToString());

        var doc = Json(RunCli("explain", path, "--json"));
        Assert.NotNull(Step(doc, "SRF (1-port)"));
        Assert.Null(Step(doc, "SRF (shunt-through)"));

        // Same part, same answer, through a different fixture — which is the point of getting the
        // fixture right rather than a coincidence.
        double mhz = double.Parse(Step(doc, "SRF (1-port)")![..^4], CultureInfo.InvariantCulture);
        Assert.InRange(mhz, SrfHz / 1e6 * 0.999, SrfHz / 1e6 * 1.001);
    }

    [Fact]
    public void ExplainReportsTheSweepAndTheReferenceBeforeAnythingDerived()
    {
        var doc = Json(RunCli("explain", WriteMlcc(), "--json"));
        Assert.Equal("2", Step(doc, "ports"));
        Assert.Contains("non-uniform", Step(doc, "sweep"), StringComparison.Ordinal);
        Assert.Equal("50 Ω", Step(doc, "reference impedance"));
    }

    // ── helpers ────────────────────────────────────────────────────────────────────────────────

    private static JsonDocument Json(CliRun run) => JsonDocument.Parse(run.StdOut);

    private static string[] Ids(JsonDocument doc) =>
        doc.RootElement.TryGetProperty("diagnostics", out var d)
            ? [.. d.EnumerateArray().Select(e => e.GetProperty("id").GetString() ?? "")]
            : [];

    private JsonDocument AssertHasDiagnostic(CliRun run, string id)
    {
        output.WriteLine(run.StdErr);
        var doc = Json(run);
        Assert.Contains(id, Ids(doc));
        return doc;
    }

    private static string? Argument(JsonDocument doc, string id, string name) =>
        doc.RootElement.GetProperty("diagnostics").EnumerateArray()
           .First(e => e.GetProperty("id").GetString() == id)
           .GetProperty("arguments").GetProperty(name).ToString();

    /// <summary>The <c>resolved</c> value of one named walk step, or null when the step reported
    /// nothing — which is an answer here, not an omission.</summary>
    private static string? Step(JsonDocument doc, string step)
    {
        foreach (var w in doc.RootElement.GetProperty("result").GetProperty("explain").GetProperty("walks").EnumerateArray())
            if (w.GetProperty("step").GetString() == step)
                return w.TryGetProperty("resolved", out var r) ? r.GetString() : null;
        return null;
    }

    private static string How(JsonDocument doc, string step) =>
        doc.RootElement.GetProperty("result").GetProperty("explain").GetProperty("walks").EnumerateArray()
           .First(w => w.GetProperty("step").GetString() == step)
           .GetProperty("how").GetString()!;

    private readonly record struct CliRun(int ExitCode, string StdOut, string StdErr);

    private CliRun RunCli(params string[] args)
    {
        var psi = new ProcessStartInfo("dotnet")
        {
            WorkingDirectory       = RepoRoot(),
            RedirectStandardOutput = true,
            RedirectStandardError  = true,
            UseShellExecute        = false,
        };
        psi.ArgumentList.Add(CliDll());
        foreach (string a in args) psi.ArgumentList.Add(a);

        using var proc = Process.Start(psi)!;
        var outTask = proc.StandardOutput.ReadToEndAsync();
        var errTask = proc.StandardError.ReadToEndAsync();
        proc.WaitForExit();
        return new CliRun(proc.ExitCode, outTask.GetAwaiter().GetResult(), errTask.GetAwaiter().GetResult());
    }

    private static string CliDll()
    {
        string cliDir = System.Reflection.CustomAttributeExtensions
            .GetCustomAttributes<System.Reflection.AssemblyMetadataAttribute>(
                typeof(TouchstoneCliVerbTests).Assembly)
            .First(a => a.Key == "CliDir").Value!;
        return Path.GetFullPath(Path.Combine(cliDir, "CircuitRF.Cli.dll"));
    }

    private static string RepoRoot()
    {
        string dir = AppContext.BaseDirectory;
        while (dir is { Length: > 0 } && !File.Exists(Path.Combine(dir, "circuitRF.slnx")))
            dir = Path.GetDirectoryName(dir) ?? "";
        return dir;
    }
}
